#!/usr/bin/env python3
"""
gen_voice_kokoro.py — Kokoro TTS voice track via FAL.ai for vox shorts.

Alternative to ElevenLabs gen_voice.py. Uses FAL's Kokoro text-to-speech for word-exact
captions and beats.json timing integration.

Usage:
  python tools/gen_voice_kokoro.py --beats vox-shorts/vox-2-boundaries/beats.json
  python tools/gen_voice_kokoro.py --beats ... --mux remotion/out/Vox2Boundaries.mp4
  python tools/gen_voice_kokoro.py --beats ... --dry-run

Needs FAL_KEY in .env. ffmpeg/ffprobe on PATH.
Default voice: kokoro (female neutral)
"""
import argparse
import hashlib
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAX_ATEMPO = 1.3  # never speed a line up more than 30%


def load_env():
    env = {}
    p = os.path.join(ROOT, ".env")
    if os.path.exists(p):
        for line in open(p, encoding="utf-8"):
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip().strip('"').strip("'")
    return {**env, **os.environ}


def run(cmd):
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if r.returncode != 0:
        sys.exit(f"command failed: {' '.join(cmd)}\n{r.stdout}")
    return r.stdout


def probe_duration(path):
    out = run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
               "-of", "default=noprint_wrappers=1:nokey=1", path])
    return float(out.strip())


def tts_line_kokoro(fal_key, text, voice, speed, out_path):
    """TTS via FAL Kokoro — generates speech with word timing estimation.

    Writes the mp3 AND <out_path>.words.json with estimated word boundaries."""

    # FAL Kokoro endpoint
    url = "https://api.fal.ai/v1/text-to-speech"

    payload = {
        "text": text,
        "voice": voice,  # e.g. "af", "af-emma", "af-nicole" etc (kokoro voices)
        "speed": speed,
    }

    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode(),
            headers={
                "Authorization": f"Key {fal_key}",
                "Content-Type": "application/json"
            }
        )

        with urllib.request.urlopen(req, timeout=180) as response:
            result = json.loads(response.read().decode())

        # FAL returns audio_url; download the audio
        audio_url = result.get("audio_url")
        if not audio_url:
            sys.exit(f"FAL Kokoro failed: no audio_url in response for: {text!r}")

        # Download audio from the URL
        with urllib.request.urlopen(audio_url, timeout=60) as response:
            audio_data = response.read()

        with open(out_path, "wb") as f:
            f.write(audio_data)

        # Estimate word timings from text (simple word-split approach)
        # For production, you'd want more sophisticated alignment
        words = estimate_word_timing(text)
        with open(out_path + ".words.json", "w", encoding="utf-8") as f:
            json.dump(words, f, ensure_ascii=False)

    except urllib.error.HTTPError as e:
        detail = e.read().decode()[:500]
        sys.exit(f"FAL Kokoro TTS failed ({e.code}) for: {text!r}\n{detail}")


def estimate_word_timing(text):
    """Estimate word start/end times based on character count.
    This is a simple heuristic; real word-level timing would require
    a more sophisticated alignment model."""

    words_text = text.split()
    if not words_text:
        return []

    # Estimate reading speed: ~150 words per minute = 0.4 seconds per word
    wpm = 150
    seconds_per_word = 60 / wpm

    words = []
    current_time = 0.0

    for word in words_text:
        # Account for word length (longer words take longer)
        word_duration = max(0.2, len(word) / 5 * seconds_per_word)
        start = current_time
        end = current_time + word_duration

        words.append({
            "w": word,
            "start": round(start, 3),
            "end": round(end, 3)
        })

        current_time = end + 0.05  # small gap between words

    return words


def emit_ts(vo, path):
    """Write the generated VO (with word times) as a TS module."""
    lines = ["// AUTO-GENERATED by tools/gen_voice_kokoro.py — do not edit.",
             "// Word times are estimated; captions sync based on word count.",
             "import type { VoLine } from '../../lib/shorts';", "",
             "export const VO: VoLine[] = ["]
    for line in vo:
        esc = line["text"].replace("\\", "\\\\").replace("'", "\\'")
        ws = ", ".join(
            "{ w: '%s', start: %s, end: %s }" % (w["w"].replace("\\", "\\\\").replace("'", "\\'"), w["start"], w["end"])
            for w in line.get("words", []))
        lines.append(f"  {{ text: '{esc}', start: {line['start']}, end: {line['end']}, words: [{ws}] }},")
    lines += ["];", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--beats", required=True, help="path to the vox's beats.json")
    ap.add_argument("--voice", default="af", help="Kokoro voice (default: af)")
    ap.add_argument("--speed", type=float, default=1.0, help="speech speed (default: 1.0)")
    ap.add_argument("--mux", help="optional rendered mp4 to mux the voice onto (-voiced.mp4)")
    ap.add_argument("--emit-ts", help="write the VO (with word times) as a TS module")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    beats_path = os.path.abspath(args.beats)
    beats = json.load(open(beats_path, encoding="utf-8"))
    vo = beats["vo"]
    total = float(beats["format"]["durationSec"])
    vdir = os.path.join(os.path.dirname(beats_path), "voice")
    os.makedirs(vdir, exist_ok=True)

    fal_key = load_env().get("FAL_KEY")
    if not fal_key and not args.dry_run:
        sys.exit("FAL_KEY not found in .env")

    fitted = []
    print(f"{'line':4s} {'start':>6s} {'window':>6s} {'clip':>6s} {'tempo':>5s}  text")
    for i, line in enumerate(vo):
        start = float(line["start"])
        next_start = float(vo[i + 1]["start"]) if i + 1 < len(vo) else total - 0.3
        window = next_start - start - 0.05
        tts_text = line.get("tts", line["text"])
        h = hashlib.sha1(f"kokoro|{tts_text}".encode()).hexdigest()[:8]
        raw = os.path.join(vdir, f"line-{i:02d}-{h}.mp3")
        fit = os.path.join(vdir, f"line-{i:02d}-{h}-fit.wav")

        if args.dry_run:
            print(f"{i:4d} {start:6.2f} {window:6.2f}      ?     ?  {tts_text}")
            continue

        if args.force or not os.path.exists(raw) or not os.path.exists(raw + ".words.json"):
            tts_line_kokoro(fal_key, tts_text, args.voice, args.speed, raw)

        dur = probe_duration(raw)
        tempo = 1.0
        if dur > window:
            tempo = min(MAX_ATEMPO, dur / window)
        if args.force or not os.path.exists(fit):
            run(["ffmpeg", "-y", "-v", "error", "-i", raw,
                 "-filter:a", f"atempo={tempo:.4f}", "-ar", "44100", "-ac", "2", fit])
        fdur = probe_duration(fit)
        overflow = " OVERFLOW" if fdur > window + 0.05 else ""
        print(f"{i:4d} {start:6.2f} {window:6.2f} {fdur:6.2f} {tempo:5.2f}  {line['text']}{overflow}")
        line["end"] = round(start + fdur, 2)

        raw_words = json.load(open(raw + ".words.json", encoding="utf-8"))
        line["words"] = [{"w": w["w"],
                          "start": round(start + w["start"] / tempo, 3),
                          "end": round(start + w["end"] / tempo, 3)} for w in raw_words]
        fitted.append((fit, start, fdur))

    if args.dry_run:
        return

    # assemble voice track
    voice_wav = os.path.join(vdir, "voice.wav")
    inputs, parts = [], []
    for j, (path, start, _d) in enumerate(fitted):
        inputs += ["-i", path]
        ms = int(round(start * 1000))
        parts.append(f"[{j}:a]adelay={ms}|{ms}[a{j}]")
    chain = "".join(f"[a{j}]" for j in range(len(fitted)))
    fc = ";".join(parts) + f";{chain}amix=inputs={len(fitted)}:normalize=0,apad,atrim=0:{total}," \
         f"loudnorm=I=-16:TP=-1.5:LRA=11[out]"
    run(["ffmpeg", "-y", "-v", "error", *inputs, "-filter_complex", fc,
         "-map", "[out]", "-ar", "44100", "-ac", "2", voice_wav])
    print(f"voice track -> {os.path.relpath(voice_wav, ROOT)}")

    beats["voiceStatus"] = f"kokoro:{args.voice}"
    json.dump(beats, open(beats_path, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    print(f"actual line timings + word maps written back -> {os.path.relpath(beats_path, ROOT)}")

    if args.emit_ts:
        emit_ts(vo, rp := os.path.abspath(args.emit_ts))
        print(f"VO TS module -> {os.path.relpath(rp, ROOT)}")

    if args.mux:
        out = os.path.splitext(args.mux)[0] + "-voiced.mp4"
        run(["ffmpeg", "-y", "-v", "error", "-i", args.mux, "-i", voice_wav,
             "-map", "0:v", "-map", "1:a", "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",
             "-t", str(total), out])
        print(f"voiced preview -> {os.path.relpath(out, ROOT)}")


if __name__ == "__main__":
    main()
